/**
* @File Name : CollectionCreationClassTest.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : July 16, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | July 16, 2025 |   | Initial Version
**/

public class CollectionCreationClassTest {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}